name: Deploy to GoDaddy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Copy config directory
      run: |
        mkdir -p out/public_html/earlthemonster.com/config
        cp config/recaptcha.php out/public_html/earlthemonster.com/config/
    
    - name: Deploy to GoDaddy
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        port: ${{ secrets.FTP_PORT }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./out/
        server-dir: public_html/earlthemonster.com/ 