name: Build and Deploy to GoDaddy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_only:
        description: 'Deploy only (skip build)'
        required: false
        type: boolean
        default: false

jobs:
  build:
    if: ${{ !inputs.deploy_only }}
    runs-on: ubuntu-latest
    outputs:
      build_dir: ${{ steps.build.outputs.build_dir }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      id: build
      run: |
        npm run build
        mkdir -p out/public_html/earlthemonster.com/config
        cp config/recaptcha.php out/public_html/earlthemonster.com/config/
      env:
        build_dir: ${{ github.workspace }}/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download build artifacts
      if: ${{ !inputs.deploy_only }}
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: out
    
    - name: Checkout repository
      if: ${{ inputs.deploy_only }}
      uses: actions/checkout@v3
    
    - name: Deploy to GoDaddy
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        port: ${{ secrets.FTP_PORT }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./out/
        server-dir: public_html/earlthemonster.com/ 